# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/vector_cat/gits/bcClean/external/libigl/external/glad/CMakeLists.txt))

/Users/vector_cat/gits/bcClean/Xcode/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/bin/cmake -H/Users/vector_cat/gits/bcClean -B/Users/vector_cat/gits/bcClean/Xcode
